preload = /home/brendan/.config/hypr/wallpapers/flying-comets-clouds.jpg
wallpaper = ,/home/brendan/.config/hypr/wallpapers/flying-comets-clouds.jpg

preload = /home/brendan/.config/hypr/wallpapers/mylightbg.png
wallpaper = /home/brendan/.config/hypr/wallpapers/mylightbg.png
splash = false


wallpaper {
    monitor = DP-2
    path = /home/brendan/.config/hypr/wallpapers/mylightbg.png
    fit_mode = cover
}
wallpaper {
    monitor = eDP-1
    path = /home/brendan/.config/hypr/wallpapers/mylightbg.png
    fit_mode = cover
}
